training_environment:
  simulation_mode: true
  log_level: "INFO"
  
rtu_devices:
  - device_id: "RTU_001"
    description: "Primary Training RTU"
    ip_address: "127.0.0.1"
    port: 20000
    dnp3_address: 1
    
    circuit_breakers:
      - id: "CB_MAIN"
        description: "Main Feeder Breaker"
        bay: "BAY_01"
        voltage_level: "13.8kV"
        points:
          status:
            group: 1
            index: 0
            event_class: 1
          trip_command:
            group: 12
            index: 0
            control_mode: "direct_operate"
          close_command:
            group: 12
            index: 1
            control_mode: "direct_operate"
            
      - id: "CB_BACKUP"
        description: "Backup Feeder Breaker"
        bay: "BAY_02"
        voltage_level: "13.8kV"
        points:
          status:
            group: 1
            index: 1
            event_class: 1
          trip_command:
            group: 12
            index: 2
            control_mode: "select_before_operate"
          close_command:
            group: 12
            index: 3
            control_mode: "select_before_operate"
            
      - id: "CB_TIE"
        description: "Tie Breaker"
        bay: "TIE_BAY"
        voltage_level: "13.8kV"
        points:
          status:
            group: 1
            index: 4
            event_class: 1
          trip_command:
            group: 12
            index: 4
            control_mode: "direct_operate"
          close_command:
            group: 12
            index: 5
            control_mode: "direct_operate"
